name: JACKs
favicon: null
layout_spectrum: 0.0342611949890852
typography_spectrum: 0.7210012194700539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5139707832131535
  lightness: 0.929462217958644
  saturation: 0.28028741595335305
  rhythmicContrast: 0.5857869754545391
purpose: []
